version: "3.8"

x-app: &x-app
  image: node:18
  volumes:
    - $PWD:$PWD

services:
  app:
    <<: *x-app
    ports:
      - 5000:5000
    expose:
      - 5000
    working_dir: $PWD
    command: yarn workspace @kanban/app run start

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - $PWD/postgres:/var/lib/postgresql/data
    restart: always
    depends_on:
      - app
      
  migrate:
    <<: *x-app
    working_dir: $PWD
    command: npx prisma db push
    depends_on:
      - postgres